# Generated by Django 4.0.1 on 2022-01-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('headimg', models.FileField(upload_to='media/img')),
                ('label', models.CharField(max_length=2, choices=(('1', 'Problem 1'), ('2', 'Problem 2'), ('3', 'Problem 3'),))),
                ('diag', models.CharField(max_length=500)),
            ],
        ),
    ]
